# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.12-alpine

# Install build dependencies
RUN apk add --no-cache build-base libffi-dev openssl-dev

WORKDIR /app

# Copy project files
COPY pyproject.toml src/ ./

# Install the package
RUN pip install --no-cache-dir .

# Unbuffered output
ENV PYTHONUNBUFFERED=1

# Set transport mode to HTTP
ENV TRANSPORT=http

# Expose default port for documentation and convenience
# Actual port is controlled by PORT env var (Smithery sets to 8081)
EXPOSE 8081

# Reset the entrypoint
ENTRYPOINT []

# Run with HTTP transport using Python module directly
# Smithery will set PORT env var and other configuration via environment variables
CMD ["python", "-m", "mcp_vertica"]
